services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}        
      POSTGRES_PASSWORD: ${DB_PASSWORD}   
      POSTGRES_DB: ${DB_NAME}   
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}        
    ports:
      - "5050:80"
    depends_on:
      - db

  etl_worker:
    build: .
    container_name: etl_pipeline_worker
    restart: on-failure
    env_file:
      - .env
    environment:
      # Перевизначаємо DB_HOST для роботи всередині Docker-мережі
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: